# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Release

on: [workflow_dispatch]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle- 

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'

      - name: Make Gradlew Executable
        run: chmod +x gradlew

      - name: Compile with Gradle
        run: ./gradlew shadowJar --no-daemon

      - name : Retrieve OS
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            echo "::set-output name=OS_NAME::windows"
          elif [ "${{ runner.os }}" == "Linux" ]; then
            echo "::set-output name=OS_NAME::linux"
          elif [ "${{ runner.os }}" == "macOS" ]; then
            echo "::set-output name=OS_NAME::macos"
          fi
        id: os_version
        shell: bash

      - name: Save OS
        run: |
          echo "os_name=${{steps.os_version.outputs.OS_NAME}}" >> $GITHUB_ENV
        shell: bash

      - name: Create Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenLightsBeatMaker-${{ env.os_name }}
          path: build/libs/
          compression-level: 0

  upload_release:
    permissions:
      contents: write
    needs: build
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Retrieve Artifacts
        uses: actions/download-artifact@v4
        with:
          path: build/libs/
          merge-multiple: true

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'

      - name: Make Gradlew Executable
        run: chmod +x gradlew

      - name: Retrieve Version
        run: |
          echo "::set-output name=VERSION_NAME::$(${{github.workspace}}/gradlew -q printVersionName)"
        id: project_version

      - name: Save Version
        run: |
          echo "version_name=${{steps.project_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV

      - name: Upload Jar
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          tag_name: ${{ env.version_name }}
          prerelease: ${{ contains(env.version_name, 'pre') || contains(env.version_name, 'beta') || contains(env.version_name, 'rc') }}
          name: Open Lights BeatMaker ${{ env.version_name }}
          files: build/libs/*.jar
          generate_release_notes: true
